// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpFL9OlmZqiDK0sLENZMuivgrsS3-cfqk',
    appId: '1:671333842660:web:93d389bffc3ca63e7676f1',
    messagingSenderId: '671333842660',
    projectId: 'mentorx-49538',
    authDomain: 'mentorx-49538.firebaseapp.com',
    storageBucket: 'mentorx-49538.appspot.com',
    measurementId: 'G-F05LN5GKBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU2WYB2ma_kNhOZ5Uej0MvOECvQ4gUiPY',
    appId: '1:671333842660:android:0c34d3855b95fa4d7676f1',
    messagingSenderId: '671333842660',
    projectId: 'mentorx-49538',
    storageBucket: 'mentorx-49538.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCjPZmJZg6ApL6PNbrEH4DmsCkrKe1F_k',
    appId: '1:671333842660:ios:537fe57bbc80d4727676f1',
    messagingSenderId: '671333842660',
    projectId: 'mentorx-49538',
    storageBucket: 'mentorx-49538.appspot.com',
    iosBundleId: 'com.example.mentorxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCjPZmJZg6ApL6PNbrEH4DmsCkrKe1F_k',
    appId: '1:671333842660:ios:b46d16cdb2055ff27676f1',
    messagingSenderId: '671333842660',
    projectId: 'mentorx-49538',
    storageBucket: 'mentorx-49538.appspot.com',
    iosBundleId: 'com.example.mentorxApp.RunnerTests',
  );
}
